import Foundation

// MARK: - V2 Command Catalog
//
// Single source of truth for the method-name list advertised by
// `system.capabilities`. This catalog mirrors (but does not drive) the
// dispatch switch in `TerminalController.processV2Command` — adding a new
// case there still requires adding the method name here so it shows up in
// capabilities. Order is preserved to match the historical literal array in
// `TerminalController.v2Capabilities()`; the final output is sorted anyway,
// but keeping the source order matching the switch makes future diffs easier
// to review.
enum V2CommandCatalog {
    /// Methods available in all build configurations (Debug and Release).
    static let baseMethods: [String] = [
        "system.ping",
        "system.capabilities",
        "system.identify",
        "system.tree",
        "auth.login",
        "window.list",
        "window.current",
        "window.focus",
        "window.create",
        "window.close",
        "workspace.list",
        "workspace.create",
        "workspace.select",
        "workspace.current",
        "workspace.close",
        "workspace.move_to_window",
        "workspace.reorder",
        "workspace.rename",
        "workspace.action",
        "workspace.next",
        "workspace.previous",
        "workspace.last",
        "workspace.equalize_splits",
        "workspace.remote.configure",
        "workspace.remote.foreground_auth_ready",
        "workspace.remote.reconnect",
        "workspace.remote.disconnect",
        "workspace.remote.status",
        "workspace.remote.terminal_session_end",
        "workspace.set_status",
        "workspace.clear_status",
        "workspace.list_status",
        "workspace.log",
        "workspace.clear_log",
        "workspace.list_log",
        "workspace.set_progress",
        "workspace.clear_progress",
        "workspace.sidebar_state",
        "workspace.clear_agent_pid",
        "workspace.set_agent_pid",
        "workspace.report_meta_block",
        "workspace.clear_meta_block",
        "workspace.list_meta_blocks",
        "workspace.reset_sidebar",
        "settings.open",
        "feedback.open",
        "feedback.submit",
        "surface.list",
        "surface.current",
        "surface.focus",
        "surface.split",
        "surface.create",
        "surface.close",
        "surface.drag_to_split",
        "surface.move",
        "surface.reorder",
        "surface.action",
        "tab.action",
        "surface.refresh",
        "surface.health",
        "debug.terminals",
        "surface.send_text",
        "surface.send_key",
        "surface.report_tty",
        "surface.ports_kick",
        "surface.read_text",
        "surface.clear_history",
        "surface.trigger_flash",
        "surface.report_pwd",
        "surface.report_shell_state",
        "surface.report_git_branch",
        "surface.clear_git_branch",
        "surface.report_pr",
        "surface.clear_pr",
        "surface.report_ports",
        "surface.clear_ports",
        "pane.list",
        "pane.focus",
        "pane.surfaces",
        "pane.create",
        "pane.resize",
        "pane.swap",
        "pane.break",
        "pane.join",
        "pane.last",
        "notification.create",
        "notification.create_for_surface",
        "notification.create_for_target",
        "notification.list",
        "notification.clear",
        "app.focus_override.set",
        "app.simulate_active",
        "app.reload_config",
        "markdown.open",
        "browser.open_split",
        "browser.navigate",
        "browser.back",
        "browser.forward",
        "browser.reload",
        "browser.url.get",
        "browser.snapshot",
        "browser.eval",
        "browser.wait",
        "browser.click",
        "browser.dblclick",
        "browser.hover",
        "browser.focus",
        "browser.type",
        "browser.fill",
        "browser.press",
        "browser.keydown",
        "browser.keyup",
        "browser.check",
        "browser.uncheck",
        "browser.select",
        "browser.scroll",
        "browser.scroll_into_view",
        "browser.screenshot",
        "browser.get.text",
        "browser.get.html",
        "browser.get.value",
        "browser.get.attr",
        "browser.get.title",
        "browser.get.count",
        "browser.get.box",
        "browser.get.styles",
        "browser.is.visible",
        "browser.is.enabled",
        "browser.is.checked",
        "browser.focus_webview",
        "browser.is_webview_focused",
        "browser.find.role",
        "browser.find.text",
        "browser.find.label",
        "browser.find.placeholder",
        "browser.find.alt",
        "browser.find.title",
        "browser.find.testid",
        "browser.find.first",
        "browser.find.last",
        "browser.find.nth",
        "browser.frame.select",
        "browser.frame.main",
        "browser.dialog.accept",
        "browser.dialog.dismiss",
        "browser.download.wait",
        "browser.cookies.get",
        "browser.cookies.set",
        "browser.cookies.clear",
        "browser.storage.get",
        "browser.storage.set",
        "browser.storage.clear",
        "browser.tab.new",
        "browser.tab.list",
        "browser.tab.switch",
        "browser.tab.close",
        "browser.console.list",
        "browser.console.clear",
        "browser.errors.list",
        "browser.highlight",
        "browser.state.save",
        "browser.state.load",
        "browser.addinitscript",
        "browser.addscript",
        "browser.addstyle",
        "browser.viewport.set",
        "browser.geolocation.set",
        "browser.offline.set",
        "browser.trace.start",
        "browser.trace.stop",
        "browser.network.route",
        "browser.network.unroute",
        "browser.network.requests",
        "browser.screencast.start",
        "browser.screencast.stop",
        "browser.input_mouse",
        "browser.input_keyboard",
        "browser.input_touch",
    ]

    /// Methods only available in DEBUG builds, appended after `baseMethods`.
    static let debugMethods: [String] = [
        "debug.shortcut.set",
        "debug.shortcut.simulate",
        "debug.type",
        "debug.app.activate",
        "debug.command_palette.toggle",
        "debug.command_palette.rename_tab.open",
        "debug.command_palette.visible",
        "debug.command_palette.selection",
        "debug.command_palette.results",
        "debug.command_palette.rename_input.interact",
        "debug.command_palette.rename_input.delete_backward",
        "debug.command_palette.rename_input.selection",
        "debug.command_palette.rename_input.select_all",
        "debug.browser.address_bar_focused",
        "debug.browser.favicon",
        "debug.sidebar.visible",
        "debug.terminal.is_focused",
        "debug.terminal.read_text",
        "debug.terminal.render_stats",
        "debug.layout",
        "debug.portal.stats",
        "debug.bonsplit_underflow.count",
        "debug.bonsplit_underflow.reset",
        "debug.empty_panel.count",
        "debug.empty_panel.reset",
        "debug.notification.focus",
        "debug.flash.count",
        "debug.flash.reset",
        "debug.panel_snapshot",
        "debug.panel_snapshot.reset",
        "debug.window.screenshot",
    ]

    /// Full method list for the current build configuration, mirroring the
    /// conditional `#if DEBUG` append that used to live inline in
    /// `TerminalController.v2Capabilities()`.
    static var methods: [String] {
        #if DEBUG
        return baseMethods + debugMethods
        #else
        return baseMethods
        #endif
    }
}
