// GENERATED FILE — do not edit by hand.
// Source of truth: contracts/v2/methods.json
// Regenerate with: python3 scripts/gen-v2-contract.py
// Verify with:      scripts/check-v2-contract.sh

import Foundation

// MARK: - V2 Command Catalog
//
// Single source of truth for the method-name list advertised by
// `system.capabilities`, generated from contracts/v2/methods.json so it cannot
// drift from the contract or from the handler dispatch switch it mirrors.
enum V2CommandCatalog {
    /// Methods available in all build configurations (Debug and Release).
    static let baseMethods: [String] = [
        "agent.detection.classify",
        "agent.detection.list",
        "agent.event",
        "agent.needs_input",
        "agent.prompt",
        "agent.spawn",
        "agent.task.finish",
        "agent.task.finish_session",
        "agent.task.list",
        "agent.task.start",
        "agent.task.update",
        "app.browsers",
        "app.reload_config",
        "auth.login",
        "feedback.open",
        "feedback.submit",
        "layout.apply",
        "layout.list",
        "layout.save",
        "markdown.open",
        "notification.clear",
        "notification.create",
        "notification.create_for_surface",
        "notification.create_for_target",
        "notification.list",
        "pane.break",
        "pane.create",
        "pane.focus",
        "pane.join",
        "pane.last",
        "pane.list",
        "pane.resize",
        "pane.surfaces",
        "pane.swap",
        "ports.list",
        "ports.stop",
        "review.comment.add",
        "review.comment.list",
        "review.comment.remove",
        "review.open",
        "review.refresh",
        "review.send_comments",
        "settings.open",
        "snapshot.list",
        "snapshot.restore",
        "subscribe",
        "surface.action",
        "surface.clear_agent_state",
        "surface.clear_git_branch",
        "surface.clear_history",
        "surface.clear_ports",
        "surface.clear_pr",
        "surface.close",
        "surface.create",
        "surface.current",
        "surface.drag_to_split",
        "surface.focus",
        "surface.health",
        "surface.list",
        "surface.move",
        "surface.ports_kick",
        "surface.read_text",
        "surface.refresh",
        "surface.reorder",
        "surface.report_agent_state",
        "surface.report_git_branch",
        "surface.report_ports",
        "surface.report_pr",
        "surface.report_pwd",
        "surface.report_shell_state",
        "surface.report_tty",
        "surface.resolve_tty",
        "surface.send_key",
        "surface.send_text",
        "surface.split",
        "surface.trigger_flash",
        "surface.wait",
        "system.capabilities",
        "system.identify",
        "system.ping",
        "system.tree",
        "tab.action",
        "unsubscribe",
        "window.close",
        "window.create",
        "window.current",
        "window.focus",
        "window.list",
        "workspace.action",
        "workspace.clear_agent_pid",
        "workspace.clear_log",
        "workspace.clear_meta_block",
        "workspace.clear_progress",
        "workspace.clear_status",
        "workspace.close",
        "workspace.create",
        "workspace.current",
        "workspace.equalize_splits",
        "workspace.last",
        "workspace.list",
        "workspace.list_log",
        "workspace.list_meta_blocks",
        "workspace.list_status",
        "workspace.log",
        "workspace.move_to_window",
        "workspace.next",
        "workspace.previous",
        "workspace.rename",
        "workspace.reorder",
        "workspace.report_meta_block",
        "workspace.reset_sidebar",
        "workspace.select",
        "workspace.set_agent_pid",
        "workspace.set_progress",
        "workspace.set_status",
        "workspace.sidebar_state",
        "worktree.create",
        "worktree.list",
        "worktree.open",
        "worktree.remove",
    ]

    /// Methods only available in DEBUG builds, appended after `baseMethods`.
    static let debugMethods: [String] = [
        "app.focus_override.set",
        "app.simulate_active",
        "debug.app.activate",
        "debug.bonsplit_underflow.count",
        "debug.bonsplit_underflow.reset",
        "debug.command_palette.rename_input.delete_backward",
        "debug.command_palette.rename_input.interact",
        "debug.command_palette.rename_input.selection",
        "debug.command_palette.rename_tab.open",
        "debug.command_palette.results",
        "debug.command_palette.selection",
        "debug.command_palette.toggle",
        "debug.command_palette.visible",
        "debug.empty_panel.count",
        "debug.empty_panel.reset",
        "debug.flash.count",
        "debug.flash.reset",
        "debug.glass.set",
        "debug.layout",
        "debug.notification.focus",
        "debug.panel_snapshot",
        "debug.panel_snapshot.reset",
        "debug.portal.stats",
        "debug.samples.reset",
        "debug.samples.stats",
        "debug.shortcut.set",
        "debug.shortcut.simulate",
        "debug.sidebar.visible",
        "debug.terminal.is_focused",
        "debug.terminal.read_text",
        "debug.terminal.render_stats",
        "debug.terminals",
        "debug.type",
        "debug.window.screenshot",
    ]

    /// Full method list for the current build configuration, mirroring the
    /// conditional `#if DEBUG` append that used to live inline in
    /// `TerminalController.v2Capabilities()`.
    static var methods: [String] {
        #if DEBUG
        return baseMethods + debugMethods
        #else
        return baseMethods
        #endif
    }
}
